server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mangastorage
    username: postgres
    password: 4710

  jpa:
    properties:
      hibernate:
    show-sql: true
    hibernate:
      ddl-auto: update
rsa:
  test:
    private-key: classpath:certs-test/private.pem
    public-key: classpath:certs-test/public.pem
